Removed EDSS references

diff --git a/scripts/make/Makeall b/scripts/make/Makeall
--- a/scripts/make/Makeall
+++ b/scripts/make/Makeall
@@ -5,25 +5,25 @@
 #
 ## Set controllers for turning on/off library building
 #
-setenv FILESET_MAKE_LIB  Y   # [ Y | N ]  # For FileSetAPI library
-setenv ETOOLS_MAKE_LIB   Y   # [ Y | N ]  # For edss_tools library
+setenv FILESET_MAKE_LIB  N   # [ Y | N ]  # For FileSetAPI library
+setenv ETOOLS_MAKE_LIB   N   # [ Y | N ]  # For edss_tools library
 setenv SMK_MAKE_LIB      Y   # [ Y | N ]  # For SMOKE library
-setenv SMK_MAKE_MOBLIB   Y   # [ Y | N ]  # For MOBILE6 library
+setenv SMK_MAKE_MOBLIB   N   # [ Y | N ]  # For MOBILE6 library
 setenv SMK_MAKE          Y   # [ Y | N ]  # For SMOKE programs
 #
-## Set the directory for the EDSS installation
-if ( $?EDSS_ROOT ) then
+## Set the directory for the SMOKE installation
+if ( $?SMK_HOME ) then
    if ( $?SMKROOT ) then
    else
-      setenv SMKROOT $EDSS_ROOT/subsys/smoke
+      setenv SMKROOT $SMK_HOME/subsys/smoke
    endif
-   if ( $?EDSS_SUBSYS ) then
+   if ( $?SMK_SUBSYS ) then
    else
-      setenv EDSS_SUBSYS $EDSS_ROOT/subsys
+      setenv SMK_SUBSYS $SMK_HOME/subsys
    endif
 else
 
-   echo "ERROR: Environment variable EDSS_ROOT needs to be set to"
+   echo "ERROR: Environment variable SMK_HOME needs to be set to"
    echo "       use this script"
    exit( 1 )
 
@@ -36,15 +36,15 @@ set what = $argv
 set outstat = 0
 
 ## Check for installation of critical files
-if ( ! -e $EDSS_ROOT/scripts/platform ) then
+if ( ! -e $SMK_HOME/scripts/platform ) then
    echo "ERROR: platform file has not been installed in"
-   echo "       $EDSS_ROOT/scripts/"
+   echo "       $SMK_HOME/scripts/"
    set outstat = 1
 endif
 
-if ( ! -e $EDSS_SUBSYS/ioapi_includes/PARMS3.EXT ) then
+if ( ! -e $SMK_SUBSYS/ioapi_includes/PARMS3.EXT ) then
    echo "ERROR: I/O API include files have not been installed in"
-   echo "       $EDSS_SUBSYS"
+   echo "       $SMK_SUBSYS"
    set outstat = 1
 endif
 
@@ -57,12 +57,12 @@ endif
 #
 if ( $FILESET_MAKE_LIB == Y ) then
    echo "Building FileSetAPI library..."
-   if ( ! -e $EDSS_SUBSYS/filesetapi ) then
+   if ( ! -e $SMK_SUBSYS/filesetapi ) then
       echo "ERROR: FileSetAPI source has not been installed in"
-      echo "       $EDSS_SUBSYS"
+      echo "       $SMK_SUBSYS"
       set outstat = 1
    else
-      cd $EDSS_SUBSYS/filesetapi
+      cd $SMK_SUBSYS/filesetapi
       source Setup
       make clean
       Makeit $argv
@@ -74,12 +74,12 @@ endif
 #
 if ( $ETOOLS_MAKE_LIB == Y ) then
    echo "Building EDSS Tools library..."
-   if ( ! -e $EDSS_SUBSYS/edss_tools ) then
+   if ( ! -e $SMK_SUBSYS/edss_tools ) then
       echo "ERROR: EDSS Tool source has not been installed in"
-      echo "       $EDSS_SUBSYS"
+      echo "       $SMK_SUBSYS"
       set outstat = 1
    else
-      cd $EDSS_SUBSYS/edss_tools/setup
+      cd $SMK_SUBSYS/edss_tools/setup
       source Setup
       cd $ETLSRC
       make clean
