Version for 1.5 SMOKE release

diff --git a/scripts/make/Makeall b/scripts/make/Makeall
--- a/scripts/make/Makeall
+++ b/scripts/make/Makeall
@@ -5,76 +5,107 @@
 #
 ## Set controllers for turning on/off library building
 #
-setenv ETOOLS_MAKE_LIB  Y   # [ Y | N ]
-setenv SMK_MAKE_LIB     Y   # [ Y | N ]
-setenv SMK_MAKE_MOBLIB  5B  # [ 5A | 5B | 6 | N ]
-
+setenv FILESET_MAKE_LIB  N   # [ Y | N ]  # For FileSetAPI library
+setenv ETOOLS_MAKE_LIB   N   # [ Y | N ]  # For edss_tools library
+setenv SMK_MAKE_LIB      N   # [ Y | N ]  # For SMOKE library
+setenv SMK_MAKE_MOBLIB   N   # [ Y | N ]  # For MOBILE6 library
+setenv SMK_MAKE          Y   # [ Y | N ]  # For SMOKE programs
 #
 ## Set the directory for the EDSS installation
-if ( $?EDSS_SUBSYS ) then
+if ( $?EDSS_ROOT ) then
    if ( $?SMKROOT ) then
    else
-      setenv SMKROOT $EDSS_SUBSYS/smokev1
+      setenv SMKROOT $EDSS_ROOT/subsys/smokev1
+   endif
+   if ( $?EDSS_SUBSYS ) then
+   else
+      setenv EDSS_SUBSYS $EDSS_ROOT/subsys
    endif
 else
 
-   echo "ERROR: Environment variable EDSS_SUBSYS needs to be set to"
+   echo "ERROR: Environment variable EDSS_ROOT needs to be set to"
    echo "       use this script"
    exit( 1 )
-
-endif
-
-#
-## Set the directory for the sysflags and smk_mkdir scripts
- 
-set assigndir = $SMKROOT/assigns
-
-#
-## Source the sysflags script to set environment variables for compiling
-#
-
-if ( ! -e $assigndir/sysflags ) then
-   echo "Cannot find sysflags file\!"
-   echo " "
-   echo "Get set up for EDSS or set SMKROOT to the"
-   echo "   path of the Assigns file."
-   exit( 1 )
-else
-
-   source $assigndir/sysflags
 
 endif
 
 ## Activate script argument
 set what = $argv
 
+## Initialize output status
+set outstat = 0
+
+## Check for installation of critical files
+if ( ! -e $EDSS_ROOT/scripts/platform ) then
+   echo "ERROR: platform file has not been installed in"
+   echo "       $EDSS_ROOT/scripts/"
+   set outstat = 1
+endif
+
+if ( ! -e $EDSS_SUBSYS/ioapi_includes/PARMS3.EXT ) then
+   echo "ERROR: I/O API include files have not been installed in"
+   echo "       $EDSS_SUBSYS"
+   set outstat = 1
+endif
+
+if ( $outstat == 1 ) then
+   exit( 1 )
+endif
+
+#
+## Make FileSetAPI library
+#
+if ( $FILESET_MAKE_LIB == Y ) then
+   echo "Building FileSetAPI library..."
+   if ( ! -e $EDSS_SUBSYS/filesetapi ) then
+      echo "ERROR: FileSetAPI source has not been installed in"
+      echo "       $EDSS_SUBSYS"
+      set outstat = 1
+   else
+      cd $EDSS_SUBSYS/filesetapi
+      source Setup
+      make clean
+      Makeit $argv
+   endif
+endif
+
 #
 ## Make EDSS tools library
 #
 if ( $ETOOLS_MAKE_LIB == Y ) then
    echo "Building EDSS Tools library..."
-   cd $EDSS_SUBSYS/edss_tools/setup
-   source Setup
-   cd $ETLSRC
-   make clean
-   Makeit $argv
+   if ( ! -e $EDSS_SUBSYS/edss_tools ) then
+      echo "ERROR: EDSS Tool source has not been installed in"
+      echo "       $EDSS_SUBSYS"
+      set outstat = 1
+   else
+      cd $EDSS_SUBSYS/edss_tools/setup
+      source Setup
+      cd $ETLSRC
+      make clean
+      Makeit $argv
+   endif
 endif
 
 #
 ## Set up for SMOKE compiling
 #
-cd $assigndir
-source $assigndir/ASSIGNS.m3demo.cb-iv.ed36
+if ( $SMK_MAKE_LIB == Y || $SMK_MAKE_MOBLIB == Y || $SMK_MAKE == Y ) then
+   if ( ! -e $SMKROOT ) then
+      echo "ERROR: SMOKE root directory not found. It was set to:"
+      echo "       $SMKROOT"
+   else
+      cd $SMKROOT/assigns
+      source sysflags
+   endif
+endif
 
-#
 ## Make SMOKE library
 #
 if ( $?SMK_MAKE_LIB ) then
 
    if ( $SMK_MAKE_LIB == 'Y' ) then
       echo "Building SMOKE library..."
-      cd $MD_SRC
-      make clean
       cd $EL_SRC
       make clean
       Makeit $argv
@@ -87,21 +118,89 @@ endif
 #
 if ( $?SMK_MAKE_MOBLIB ) then
 
-   if ( $SMK_MAKE_MOBLIB == '5A' ) then
-      echo 'NOTE: Mobile5a library build not supported in this version'
-   endif 
-
-   if ( $SMK_MAKE_MOBLIB == '5B' ) then
-      echo "Building Mobile5b library..."
-      cd $M5_SRC
-      make $argv
-   endif 
-
-   if ( $SMK_MAKE_MOBLIB == '6' ) then
-      echo 'NOTE: Mobile6 library build not supported in this version'
-      
+   if ( $SMK_MAKE_MOBLIB == 'Y' ) then
+      echo "Building MOBILE6 library..."
+      cd $M6_SRC 
+      make clean
+      Makeit $argv
    endif
 
+endif
+
+if ( $SMK_MAKE == Y ) then
+
+#
+## Check that I/O API and NetCDF libaries have been installed, try to link files
+#
+if ( $argv == debug ) then
+   if ( ! -e $SMK_BIN/libsmoke.debug.a ) then
+      echo "ERROR: SMOKE debug library libsmoke.debug.a is"
+      echo "       missing from SMK_BIN directory:"
+      echo "       $SMK_BIN"
+      set outstat = 1
+   endif
+   if ( ! -e $TOOLS_BIN/libedsstools.debug.a ) then
+      echo "ERROR: EDSS Tools debug library libedsstools.debug.a is"
+      echo "       missing from TOOLS_BIN directory:"
+      echo "       $TOOLS_BIN"
+      set outstat = 1
+   endif
+   if ( ! -e $FS_BIN/libfileset.debug.a ) then
+      echo "ERROR: FileSetAPI debug library libfileset.debug.a is"
+      echo "       missing from FS_BIN directory:"
+      echo "       $FS_BIN"
+      set outstat = 1
+   endif
+   if ( ! -e $IOAPIDIR/libioapi.debug.a ) then
+      echo "ERROR: I/O API debug library libioapi.debug.a is"
+      echo "       missing from IOAPIDIR directory:"
+      echo "       $IOAPIDIR"
+      set outstat = 1
+   endif
+   if ( ! -e $NETCDFDIR/libnetcdf.debug.a ) then
+      echo "ERROR: NETCDF debug library libnetcdf.debug.a is"
+      echo "       missing from NETCDFDIR directory:"
+      echo "       $NETCDFDIR"
+      set outstat = 1
+   endif
+else
+   if ( ! -e $SMK_BIN/libsmoke.a ) then
+      echo "ERROR: SMOKE library libsmoke.a is"
+      echo "       missing from SMK_BIN directory:"
+      echo "       $SMK_BIN"
+      set outstat = 1
+   endif
+   if ( ! -e $TOOLS_BIN/libedsstools.a ) then
+      echo "ERROR: EDSS Tools library libedsstools.a is"
+      echo "       missing from TOOLS_BIN directory:"
+      echo "       $TOOLS_BIN"
+      set outstat = 1
+   endif
+   if ( ! -e $FS_BIN/libfileset.a ) then
+      echo "ERROR: FileSetAPI library libfileset.a is"
+      echo "       missing from FS_BIN directory:"
+      echo "       $FS_BIN"
+      set outstat = 1
+   endif
+   if ( ! -e $IOAPIDIR/libioapi.a ) then
+      echo "ERROR: I/O API library libioapi.a is"
+      echo "       missing from IOAPIDIR directory:"
+      echo "       $IOAPIDIR"
+      set outstat = 1
+   endif
+   if ( ! -e $NETCDFDIR/libnetcdf.a ) then
+      echo "ERROR: NETCDF library libnetcdf.a is"
+      echo "       missing from NETCDFDIR directory:"
+      echo "       $NETCDFDIR"
+      set outstat = 1
+   endif
+endif
+
+#
+## Abort if libraries are not okay
+#
+if ( $outstat == 1 ) then
+   exit( 1 )
 endif
 
 #
@@ -132,7 +231,7 @@ cd $TM_SRC     # Temporal
 make clean
 Makeit $argv    
 
-echo "Building Rawbio and Tmpbio..."
+echo "Building Rawbio, Tmpbio, Beis3, and Normbeis3..."
 cd $BG_SRC    # Rawbio and Tmpbio
 make clean
 Makeit $argv
@@ -161,6 +260,8 @@ echo "Building Quality Assurance..."
 cd $QA_SRC     # Smkreport
 make clean
 Makeit $argv
+
+endif
 
 
 exit( 0 )
