Initial revision In preparation for SMOKE v1.5 release

diff --git a/assigns/smk_mkdir b/assigns/smk_mkdir
--- a/assigns/smk_mkdir
+++ b/assigns/smk_mkdir
@@ -1,11 +1,20 @@
 #!/bin/csh -f
+# $Id$
 
    ### Set umask to be group writable, world read and execute
    umask 2
 
    ### Make input and output director(ies) #######
    if ( -e $SMKDAT ) then
-       if( ! -e $INVDIR ) mkdir -p $INVDIR
+       if( ! -e $INVDIR ) then
+           mkdir -p $INVDIR/area 
+           mkdir -p $INVDIR/nonroad 
+           mkdir -p $INVDIR/biog
+           mkdir -p $INVDIR/point 
+           mkdir -p $INVDIR/mobile 
+           mkdir -p $INVDIR/other
+       endif
+       if( ! -e $GE_DAT ) mkdir -p $GE_DAT
        if( ! -e $INVOPD ) mkdir -p $INVOPD
        if( ! -e $A_OUT )  mkdir -p $A_OUT
        if( ! -e $B_OUT )  mkdir -p $B_OUT
@@ -13,6 +22,12 @@
        if( ! -e $P_OUT )  mkdir -p $P_OUT
        if( ! -e $OUTPUT ) mkdir -p $OUTPUT
        if( ! -e $STATIC ) mkdir -p $STATIC
+       if( ! -e $SMK_TMPDIR ) mkdir -p $SMK_TMPDIR  
+       if( ! -e $SMK_METPATH ) mkdir -p $SMK_METPATH
+       if( ! -e $SMK_SPDPATH ) mkdir -p $SMK_SPDPATH
+       if( ! -e $SMK_M6PATH  ) mkdir -p $SMK_M6PATH
+       if( ! -e $SMK_EMISPATH ) mkdir -p $SMK_EMISPATH
+       if( ! -e $LOGS   ) mkdir -p $LOGS  
        if( ! -e $BASDIR ) mkdir -p $BASDIR
        if( ! -e $REPSCEN ) mkdir -p $REPSCEN
        if( ! -e $REPSTAT ) mkdir -p $REPSTAT
@@ -24,16 +39,21 @@
        if( ! -e $REPORTS/$MSCEN/static )  mkdir -p $REPORTS/$MSCEN/static
        if( ! -e $REPORTS/$PSCEN/$ESDATE ) mkdir -p $REPORTS/$PSCEN/$ESDATE
        if( ! -e $REPORTS/$PSCEN/static )  mkdir -p $REPORTS/$PSCEN/static
-  else
-       echo "ERROR: Create the SMOKE data directory\!"
+   else
+       echo "ERROR: The SMOKE data directory does not exist!"
+       echo "       Please check to make sure that the following"
+       echo "       path is valid:"
+       echo "       $SMKDAT"
        exit( 1 )
    endif
 
    ### Check permissions on output directories ####
    set user = `whoami`
-   foreach dir ( $INVDIR $INVOPD $SCENARIO $STATIC $A_OUT $B_OUT $M_OUT \
+   foreach dir ( $INVDIR $INVDIR/area $INVDIR/nonroad $INVDIR/biog $INVDIR/mobile $INVDIR/point \
+                 $INVDIR/other $INVOPD $SCENARIO $STATIC $A_OUT $B_OUT $M_OUT \
                  $P_OUT $OUTPUT $BASDIR $REPORTS/$ASCEN $REPORTS/$BSCEN \
-                 $REPORTS/$MSCEN $REPORTS/$PSCEN $REPSCEN $REPSTAT )
+                 $REPORTS/$MSCEN $REPORTS/$PSCEN $REPSCEN $REPSTAT $SMK_TMPDIR $SMK_METPATH \
+                 $SMK_SPDPATH $SMK_M6PATH $SMK_EMISPATH )
 
        set line   = ( `/bin/ls -ld $dir` )
        set owner  = $line[3]
@@ -57,5 +77,15 @@
        endif
 
    end
+
+   ## Check length of directory names with constrained lengths
+   if ( $?SMK_M6PATH ) then
+      set cnt = `echo $SMK_M6PATH | wc -c`
+      @ cnt = $cnt - 1
+      if ( $cnt > 50 ) then
+         echo "NOTE: 
+         status = 1
+      endif
+   endif
 
    cd $ASSIGNS
